Hw3
illalinalli/java-course-2023 pull request #7
Opened 2023-10-29 13:05 UTC by illalinalli

2023-10-30 20:36 UTC, psharaev requested changes
Пометки:
🔴 Критичные комментарии, необходимо всех их устранить;
🟡 Общепринятый стиль написания кода на Java, так же обязательно к исправлению;
🟢 Нетривиальные правки и без них поставлю полный балл, но я порадуюсь, если вы их сделаете.

2023-10-30 20:36 UTC, psharaev commented on project-template/src/main/java/edu/hw3/task2/Сlusterize.java
> +        Stack<Integer> stack = new Stack<>();
🔴 Не надо использовать `Stack`, неожиданно, но он работает медленно т.к. берёт блокировку под капотом. Используйте `ArrayList` как стек

2023-10-30 20:36 UTC, psharaev commented on project-template/src/main/java/edu/hw3/task6/StockMarketImpl.java
> +        stocks = new PriorityQueue<>((s1, s2) -> Double.compare(s2.getPrice(), s1.getPrice()));
🔴 Можно написать короче `new PriorityQueue<>(Comparator.comparingDouble(Stock::getPrice))`

2023-10-30 20:36 UTC, psharaev commented on project-template/src/main/java/edu/hw3/task7/NullComparator.java
> +        return ((Comparable<T>) o1).compareTo(o2);
🟡 Вам явно лучше подойдёт:
```java
Comparator.nullsFirst(
        Comparator.<String>comparing(s -> s)
);
```
(в задании не требовались дженерики, так что можете использовать строки)

2023-10-30 20:36 UTC, psharaev commented on project-template/src/main/java/edu/hw3/task8/BackwardIterator.java
> +    public BackwardIterator(List<T> list) {
🔴 В конструкторе требовалось `Collection<E> collection`. По месту можете сделать копию коллекции в лист

2023-11-03 14:01 UTC, psharaev approved these changes

2023-11-03 14:01 UTC, psharaev commented on project-template/src/main/java/edu/hw3/task7/NullComparator.java
> +        return Comparator.nullsFirst(
А зачем проверки до этого? На самом вам не нужен класс `NullComparator`, вы написали его логику в последнем `return`

2023-11-03 14:01 UTC, psharaev commented
Принято. У меня нет прав на слияние PR. Можете, пожалуйста, сделать merge

2023-11-03 14:59 UTC, illalinalli commented on project-template/src/main/java/edu/hw3/task7/NullComparator.java
> +        return Comparator.nullsFirst(
Да, поняла. Лишнее написала

2023-11-03 17:29 UTC, merged